# Generated by Django 4.1.3 on 2022-12-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="image",
        ),
        migrations.RemoveField(
            model_name="project",
            name="url",
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
