# Generated by Django 4.1.3 on 2022-12-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_remove_project_image_remove_project_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.ImageField(
                default="SOME STRING", upload_to="portfolio/images/"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.CharField(default="SOME STRING", max_length=250),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(default="SOME STRING", max_length=100),
        ),
    ]
