# Generated by Django 4.1.3 on 2022-12-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio",
            "0003_project_image_project_url_alter_project_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(upload_to="portfolio/images/"),
        ),
    ]
